services:
  fa-ms-dev:
    container_name: fa-ms-dev
    image: fa-ms-dev
    restart: "no" # unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      # ✨ Target the dev stage
      target: development
      args:
        BUILD_ENV: development
    env_file:
      - .env.development
    environment:
      - INSIDE_DOCKER=1
    # 'Ports' propels the reach of your Docker containers to the host machine and beyond, whereas 'expose' retains the communication within the Docker network.
    expose:
      - ${PORT}
    # ports:
    #   - ${PORT}:${PORT}
    # command: npm run start:dev
    networks:
      - fa-ms-development
      - jim-caddy_default
    # https://stackoverflow.com/a/62128945/19504610
    links:
      - fa-ms-dev-redis-server
      - fa-ms-dev-database
    depends_on:
      fa-ms-dev-redis-server:
        condition: service_started
      fa-ms-dev-database:
        condition: service_started

  fa-ms-dev-database:
    image: bitnami/postgresql:latest
    restart: always
    container_name: fa-ms-dev-database
    env_file: 
      - .env.development
      - secrets/.db.development
    user: root
    volumes:
      - ./docker-volumes/fa-ms-dev-database:/bitnami/postgresql
    ports:
      - ${DATABASE_PORT}:5432 # Remove this on production
    expose:
      - 5432

networks:
  fa-ms-development:
  jim-caddy_default:
    external: true