services:
  fa-ms-prod:
    container_name: fa-ms-prod
    image: fa-ms-prod
    restart: no # unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      # ✨ Target the dev stage
      target: production
      args:
        BUILD_ENV: production
    env_file:
      - .env.production
    environment:
      - INSIDE_DOCKER=1
    # 'Ports' propels the reach of your Docker containers to the host machine and beyond, whereas 'expose' retains the communication within the Docker network.
    expose:
      - ${PORT}
    networks:
      - fa-ms-production
      - jim-caddy_default
    # https://stackoverflow.com/a/62128945/19504610
    links:
      - fa-ms-prod-redis-server
    depends_on:
      fa-ms-prod-redis-server:
        condition: service_started
      fa-ms-prod-database:
        condition: service_started


  fa-ms-prod-redis-server:
    container_name: fa-ms-prod-redis-server
    image: "redis:alpine"
    restart: always
    env_file: 
      - .env.production
    command: "--port ${REDIS_PORT}"
    expose:
      - ${REDIS_PORT}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - fa-ms-production
  
  fa-ms-prod-database:
    image: bitnami/postgresql:latest
    restart: always
    container_name: fa-ms-prod-database
    env_file: 
      - .env.production
      - secrets/.db.production
    user: root
    volumes:
      - ./docker-volumes/fa-ms-prod-database:/bitnami/postgresql
    ports:
      - ${DATABASE_PORT}:5432 # Remove this on production
    expose:
      - 5432

networks:
  fa-ms-production: